// This file is autogenerated by "go generate". Do not modify it.
// It has been generated from your 'bitbucket.yaml' file.
// To update those structure, update the 'bitbucket.yaml' and run 'go generate'
package main

// Object app groups structure

// Groups structure


// Object Instance structures

type AppInstanceStruct struct {
	ForjjInfra string `json:"forjj-infra"` // Name of the Infra repository to use in github if requested.
	ForjjTeam string `json:"forjj-team"` // Default FORJJ team. Used by default as bitbucket team. If you want different one, use --bitbucket-team
	Key string `json:"key"` // Bitbucket key to access.
	ProDeployment string `json:"pro-deployment"` // true if current deployment is production one
	ProductionTeam string `json:"production-team"` // Production github organization name. By default, it uses the FORJJ organization name
	ProjectKey string `json:"project-key"` // Project key for repositories
	ReposDisabled string `json:"repos-disabled"` // true if the plugin should not manage github repositories except the infra repository.
	ReposWebhooksDisabled string `json:"repos-webhooks-disabled"` // true if the plugin should not manage github repositories webhooks.
	Secret string `json:"secret"` // Bitbucket secret to access.
	Server string `json:"server"` // Github Enterprise Server name. By default, public 'github.com' API is used.
	Team string `json:"team"` // Bitbucket team name.
	TeamHookPolicy string `json:"team-hook-policy"` // Set 'sync' to manage all repository webhooks. set 'manage' to manage only listed.
	TeamWebhooksDisabled string `json:"team-webhooks-disabled"` // true if the plugin should not manage github organization webhooks.
	TeamsDisabled string `json:"teams-disabled"` // true if the plugin should not manage github users and groups

}

// Object group groups structure

// Groups structure


// Object Instance structures

type GroupInstanceStruct struct {
	Members []string `json:"members"` // List of users to attach to the new group.
	Name string `json:"name"` // group name
	Role string `json:"role"` // List of roles to apply to the new group.

}

// Object repo groups structure

// Groups structure


// Object Instance structures

type RepoInstanceStruct struct {
	Deployable string `json:"Deployable"` // true if the repo is identified by forjj as deployable in the current deployment context
	Flow string `json:"flow"` // Flow activated on this repository
	ForjjWorkspaceMount string `json:"forjj-workspace-mount"` // Where the workspace dir is located in the github plugin container.
	Groups string `json:"groups"` // List of groups to attach to the repository, separated by comma.
	Issue_tracker string `json:"issue_tracker"` // To activate the Issue tracker to the Repository
	Name string `json:"name"` // Repository name
	Role string `json:"role"` // Role of the repository. Forjj will set it to 'infra', 'deploy' or 'code'
	Title string `json:"title"` // Github Repository title
	Users string `json:"users"` // List of users to attach to the repository, separated by comma.
	WebhooksManagement string `json:"webhooks-management"` // Set 'sync' to manage all repository webhooks. set 'manage' to manage only listed.

}

// Object user groups structure

// Groups structure


// Object Instance structures

type UserInstanceStruct struct {
	Name string `json:"name"` // 
	Role string `json:"role"` // 

}

// Object webhooks groups structure

// Groups structure


// Object Instance structures

type WebhooksInstanceStruct struct {
	Enabled string `json:"enabled"` // set 'true' (default) to activate the webhook, 'false' otherwise or 'ignore' to ignore this setup.
	Events string `json:"events"` // events requested separated by comma
	Name string `json:"name"` // webhook name
	PayloadFormat string `json:"payload-format"` // The media type used to serialize the payloads. Supported values include json and form. The default is form.
	Repos string `json:"repos"` // List of repos separated by comma subscribing to the webhook.
	SslCheck string `json:"ssl-check"` // true (default) to ask bitbucket to verify the SSL.
	Team string `json:"team"` // List to enable the webhook at team level. default is false.
	Url string `json:"url"` // Webhook url to set

}


// ************************
// Create request structure
// ************************

type ForjCommonStruct struct {
	ForjjDeploymentEnv  string `json:"deployment-env"`  // Deployment environment name
	ForjjDeploymentType string `json:"deployment-type"` // Deployment environment type
	BitbucketDebug string `json:"bitbucket-debug"`
	ForjjDeployMount string `json:"forjj-deploy-mount"`
	ForjjInfra string `json:"forjj-infra"`
	ForjjInstanceName string `json:"forjj-instance-name"`
	ForjjOrganization string `json:"forjj-organization"`
	ForjjSourceMount string `json:"forjj-source-mount"`
}

type CreateReq struct {
	Forj struct {
		ForjCommonStruct
	}

	Objects CreateArgReq

	Creds map[string]string
}

type CreateArgReq struct {
	App map[string]AppInstanceStruct `json:"app"` // Object details
	Group map[string]GroupInstanceStruct `json:"group"` // Object details
	Repo map[string]RepoInstanceStruct `json:"repo"` // Object details
	User map[string]UserInstanceStruct `json:"user"` // Object details
	Webhooks map[string]WebhooksInstanceStruct `json:"webhooks"` // Object details
}

// ************************
// Update request structure
// ************************

type UpdateReq struct {
	Forj struct {
		ForjCommonStruct
	}

	Objects UpdateArgReq

	Creds map[string]string
}

type UpdateArgReq struct {
	App map[string]AppInstanceStruct `json:"app"` // Object details
	Group map[string]GroupInstanceStruct `json:"group"` // Object details
	Repo map[string]RepoInstanceStruct `json:"repo"` // Object details
	User map[string]UserInstanceStruct `json:"user"` // Object details
	Webhooks map[string]WebhooksInstanceStruct `json:"webhooks"` // Object details
}

// **************************
// Maintain request structure
// **************************

type MaintainReq struct {
	Forj struct {
		ForjCommonStruct
		DeployTo string `json:"deploy-to"`
		Force string `json:"force"`
		ForjjWorkspaceMount string `json:"forjj-workspace-mount"`
	}

	Objects MaintainArgReq

	Creds map[string]string
}

type MaintainArgReq struct {
	App map[string]AppMaintainStruct `json:"app"` // Object details
}

type AppMaintainStruct struct {
	Key string `json:"key"` // Bitbucket key to access.
	Secret string `json:"secret"` // Bitbucket secret to access.
}


// YamlDesc has been created from your 'bitbucket.yaml' file.
const YamlDesc = "---\n" +
   "plugin: \"bitbucket\"\n" +
   "version: \"0.1\"\n" +
   "description: \"bitbucket plugin for FORJJ.\"\n" +
   "runtime:\n" +
   "  docker_image: \"docker.hos.hpecorp.net/forjj/bitbucket\"\n" +
   "  service_type: \"REST API\"\n" +
   "  service:\n" +
   "    #socket: \"bitbucket.sock\"\n" +
   "    parameters: [ \"service\", \"start\" ]\n" +
   "created_flag_file: \"{{ .InstanceName }}/forjj-{{ .Name }}.yaml\"\n" +
   "task_flags:\n" +
   "  common:\n" +
   "    forjj-infra:\n" +
   "      help: \"Name of the Infra repository to use\"\n" +
   "    bitbucket-debug:\n" +
   "      help: \"To activate bitbucket debug information\"\n" +
   "    forjj-source-mount: # Used by the plugin to store plugin data in yaml. See bitbucket_plugin.go\n" +
   "      help: \"Where the source dir is located for bitbucket plugin.\"\n" +
   "    forjj-instance-name:\n" +
   "    forjj-deploy-mount:\n" +
   "    forjj-organization:\n" +
   "  maintain:\n" +
   "    deploy-to:\n" +
   "      default: docker\n" +
   "    forjj-workspace-mount:\n" +
   "      help: \"Where the workspace dir is located in the bitbucket plugin container\"\n" +
   "    force:\n" +
   "      help: Set 'true' to force removal of teams/users when forjj creates a new forge.\n" +
   "objects: # All objects will be delivered by forjj except workspace/infra under objects/<type>/<instance>/<action>/key=value\n" +
   "  # Define infra object special flag for github\n" +
   "  app: # already defined by Forjj\n" +
   "    # Default is : actions: [\"add\", \"change\", \"remove\"] No need to define it.\n" +
   "    flags:\n" +
   "      server:\n" +
   "        help: \"Github Enterprise Server name. By default, public 'github.com' API is used.\"\n" +
   "      forjj-team:\n" +
   "        only-for-actions: [\"add\"]\n" +
   "        help: \"Default FORJJ team. Used by default as bitbucket team. If you want different one, use --bitbucket-team\"\n" +
   "#      organization:\n" +
   " #       only-for-actions: [\"add\"]\n" +
   "  #      help: \"Github Organization name. By default, it uses the FORJJ organization name\"\n" +
   "      team:\n" +
   "        only-for-actions: [\"add\"]\n" +
   "        help: \"Bitbucket team name.\"\n" +
   "      production-team:\n" +
   "        help: \"Production github organization name. By default, it uses the FORJJ organization name\"\n" +
   "        default: \"{{ .Deployments.GetFromPRO \\\"app\\\" .Current.Name \\\"organization\\\" }}\"\n" +
   "      forjj-infra:\n" +
   "        only-for-actions: [\"add\", \"change\"]\n" +
   "        help: \"Name of the Infra repository to use in github if requested.\"\n" +
   "   #   token:\n" +
   "   #     cli-exported-to-actions: [\"create\", \"update\", \"maintain\"]\n" +
   "   #     only-for-actions: [\"add\", \"change\"]\n" +
   "   #     help: \"Github token to access. This token must authorize organization level access.\"\n" +
   "   #     required: true\n" +
   "   #     secure: true\n" +
   "   #     envar: \"TOKEN\"\n" +
   "      key:\n" +
   "        cli-exported-to-actions: [\"create\", \"update\", \"maintain\"]\n" +
   "        only-for-actions: [\"add\", \"change\"]\n" +
   "        help: \"Bitbucket key to access.\"\n" +
   "        required: true\n" +
   "        secure: true\n" +
   "        envar: \"KEY\"\n" +
   "      secret:\n" +
   "        cli-exported-to-actions: [\"create\", \"update\", \"maintain\"]\n" +
   "        only-for-actions: [\"add\", \"change\"]\n" +
   "        help: \"Bitbucket secret to access.\"\n" +
   "        required: true\n" +
   "        secure: true\n" +
   "        envar: \"SECRET\"\n" +
   "      project-key:\n" +
   "        help: \"Project key for repositories\"\n" +
   "        default: \"MyProject\"\n" +
   "      teams-disabled:\n" +
   "        help: \"true if the plugin should not manage github users and groups\"\n" +
   "        default: false\n" +
   "      repos-disabled:\n" +
   "        help: \"true if the plugin should not manage github repositories except the infra repository.\"\n" +
   "        default: false\n" +
   "      team-webhooks-disabled:\n" +
   "        help: true if the plugin should not manage github organization webhooks.\n" +
   "        default: false\n" +
   "      repos-webhooks-disabled:\n" +
   "        help: true if the plugin should not manage github repositories webhooks.\n" +
   "        default: false\n" +
   "      team-hook-policy:\n" +
   "        help: Set 'sync' to manage all repository webhooks. set 'manage' to manage only listed.\n" +
   "        default: sync\n" +
   "      pro-deployment:\n" +
   "        help: true if current deployment is production one\n" +
   "        default: \"{{ if (eq (.Deployments.Get .Current.Deployment).Type \\\"PRO\\\") }}true{{ else }}false{{ end }}\"\n" +
   "  # Define github group exposure to forjj\n" +
   "  group: # New object type in forjj\n" +
   "    # Default is : actions: [\"add\", \"change\", \"remove\", \"list\", \"rename\"]\n" +
   "    help: \"Manage teams in github\"\n" +
   "    identified_by_flag: name\n" +
   "    flags:\n" +
   "      members:\n" +
   "        only-for-actions: [\"add\"]\n" +
   "        help: \"List of users to attach to the new group.\"\n" +
   "        of-type: \"[]string\"\n" +
   "      name:\n" +
   "        help: \"group name\"\n" +
   "        required: true\n" +
   "      role:\n" +
   "        only-for-actions: [\"add\"]\n" +
   "        help: \"List of roles to apply to the new group.\"\n" +
   "  # Define github users exposure to forjj\n" +
   "  user: # New object type in forjj\n" +
   "    # Default is : actions: [\"add\", \"change\", \"remove\", \"list\", \"rename\"]\n" +
   "    help: \"Manage organization list of users\"\n" +
   "    identified_by_flag: name\n" +
   "    flags:\n" +
   "      name:\n" +
   "        options:\n" +
   "          help: \"user name\"\n" +
   "          required: true\n" +
   "      role:\n" +
   "        only-for-actions: [\"add\"]\n" +
   "        options:\n" +
   "          help: \"List of roles to apply to the new user.\"\n" +
   "  repo: # Enhance Forjj repo object\n" +
   "    actions: [\"add\", \"change\"]\n" +
   "    flags:\n" +
   "      name:\n" +
   "        help: \"Repository name\"\n" +
   "      title:\n" +
   "        help: \"Github Repository title\"\n" +
   "      issue_tracker:\n" +
   "        help: \"To activate the Issue tracker to the Repository\"\n" +
   "        default: \"true\"\n" +
   "      users:\n" +
   "        only-for-actions: [\"add\"]\n" +
   "        help: \"List of users to attach to the repository, separated by comma.\"\n" +
   "        format-regexp: \"[+-]?[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?([a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9]))*,\"\n" +
   "      groups:\n" +
   "        only-for-actions: [\"add\"]\n" +
   "        help: \"List of groups to attach to the repository, separated by comma.\"\n" +
   "        format-regexp: \"[+-]?[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?([a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9]))*,\"\n" +
   "      flow:\n" +
   "        help: \"Flow activated on this repository\"\n" +
   "      forjj-workspace-mount:\n" +
   "        help: \"Where the workspace dir is located in the github plugin container.\"\n" +
   "      webhooks-management:\n" +
   "        help: Set 'sync' to manage all repository webhooks. set 'manage' to manage only listed.\n" +
   "        default: sync\n" +
   "      role:\n" +
   "        help: Role of the repository. Forjj will set it to 'infra', 'deploy' or 'code'\n" +
   "      Deployable:\n" +
   "        internal: true\n" +
   "        help: true if the repo is identified by forjj as deployable in the current deployment context\n" +
   "        default: \"{{ if (index .Forjfile.Repos .Current.Name).IsDeployable }}true{{ end }}\"\n" +
   "  webhooks:\n" +
   "    identified_by_flag: name\n" +
   "    flags:\n" +
   "      name:\n" +
   "        help: webhook name\n" +
   "        require: true\n" +
   "      url:\n" +
   "        help: Webhook url to set\n" +
   "      payload-format:\n" +
   "        help: The media type used to serialize the payloads. Supported values include json and form. The default is form.\n" +
   "        default: form\n" +
   "      events:\n" +
   "        help: events requested separated by comma\n" +
   "      repos:\n" +
   "        help: List of repos separated by comma subscribing to the webhook.\n" +
   "      team:\n" +
   "        help: List to enable the webhook at team level. default is false.\n" +
   "        default: false\n" +
   "      enabled:\n" +
   "        help: set 'true' (default) to activate the webhook, 'false' otherwise or 'ignore' to ignore this setup.\n" +
   "        default: true\n" +
   "      ssl-check:\n" +
   "        help: true (default) to ask bitbucket to verify the SSL.\n" +
   "        default: true\n" +
   ""
